### ISSUE TITLE
Publish on PyPI?

### ISSUE THREAD

**Issue by madig** [daltonmaag/vttLib#12]
Why is this package not on PyPI?

**Comment by anthrotype** [comment]
because originally it was meant to be integrated into fonttools but then that didn't happen, a bit because we didn't deem it ready at the time, but also perhaps because of lack of interest as we were the only users.
ah, another reason was that it requires pyparsing and many fonttools devs have an aversion for third party modules and prefer to reinvent the wheel

**Comment by madig** [comment]
Oh well. How about a standalone publication on PyPI then?

**Comment by anthrotype** [comment]
i'm no longer the maintainer for this package. It's up to @moyogo or @belluzj to decide

**Comment by madig** [comment]
Later, when the module is more generally useful maybe.

**Comment by m4rc1e** [comment]
@madig googlefonts now finds this tool incredibly useful. Could you kindly push v0.8.0?

**Comment by madig** [comment]
https://pypi.org/project/vttLib/

**Comment by m4rc1e** [comment]
If you're at Type Tech, I owe you a beer.
